GET http://localhost:3000/users
Authorization: Bearer 
###

GET http://localhost:3000/users/1
Authorization: Bearer 
###


POST http://localhost:3000/users/createDump
Content-Type: application/json

{
    "name": "Lorem Ipsum",
    "email": "lorem@ipsum.com",
    "gender": "Male",
    "username" :"admin",
    "password": "12341234"
}
###


POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer 

{
    "name": "Lorem Ipsum",
    "email": "lorem@ipsum.com",
    "gender": "Male",
    "username" :"admin",
    "password": "12341234"
}
###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username" :"admin",
    "password": "12341234"
}
###
PATCH  http://localhost:3000/users/1
Content-Type: application/json
Authorization: Bearer 

{
    "name": "Lorem Ipsum2",
    "email": "lorem@ipsum.com",
    "gender": "Male"
}

###
DELETE http://localhost:3000/users/3
Authorization: Bearer 
